  - name: copy catalogue service file 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service  

  - name: daemond reload and enable start catalogue
    ansible.builtin.systemd_service:
      daemon_reload: true
      
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes